/* File generated by aws2c */

#define DSIZE 58
#define RSIZE 8
#define OSIZE 8
#define GAMEN "Dawn patrol"
#define DICTHASH
#define DIR_REDUCED
#define NOSIZEWEIGHT
#define NOLONGDESC
#define BYTEROOMCODE
#define BYTEOBJCODE
#define ADVERBTYPE unsigned char
#define ADJECTIVETYPE unsigned char
#define ACTORTYPE unsigned char
#define NOADJECTIVES
#define AVOID_SDESC
